function out=supportedImageFormat(file)
[~,~,ext] = fileparts(file);
if ext; 
    if ~isempty(regexpi(ext,'bmp')) || ~isempty(regexpi(ext,'gif')) || ...
        ~isempty(regexpi(ext,'hdf')) || ~isempty(regexpi(ext,'jpeg')) || ...
        ~isempty(regexpi(ext,'jpg')) || ~isempty(regexpi(ext,'jp2')) || ...
        ~isempty(regexpi(ext,'jpf')) || ~isempty(regexpi(ext,'jpx')) || ...
        ~isempty(regexpi(ext,'j2c')) || ~isempty(regexpi(ext,'j2k')) || ...
        ~isempty(regexpi(ext,'pbm')) || ~isempty(regexpi(ext,'pcx')) || ...
        ~isempty(regexpi(ext,'pgm')) || ~isempty(regexpi(ext,'png')) || ...
        ~isempty(regexpi(ext,'pnm')) || ~isempty(regexpi(ext,'ppm')) || ...
        ~isempty(regexpi(ext,'ras')) || ~isempty(regexpi(ext,'tiff')) || ...
        ~isempty(regexpi(ext,'xwd')) || ~isempty(regexpi(ext,'cur')) || ...
        ~isempty(regexpi(ext,'fits')) || ~isempty(regexpi(ext,'ico')),
        out = true;
    else
        out = false;
    end
else
    out = true;
end