function [outputnumber] = showBottonBar( win, bottomBar, framesNumber)
%BOTTONBAR show botton bar for sync signal
%   
    if bottomBar.is
        Screen('FillRect', win,[bottomBar.baseR+bottomBar.r*mod(framesNumber,bottomBar.division) ...
            bottomBar.baseG+bottomBar.g*mod(framesNumber,bottomBar.division) ...
            bottomBar.baseB+bottomBar.b*mod(framesNumber,bottomBar.division)], ...
            [bottomBar.posLeft ...
            bottomBar.posTop ...
            bottomBar.posRight ...
            bottomBar.posBottom]);
        outputnumber = framesNumber + 1;
    else
        outputnumber = framesNumber;
    end

end

